# Generated by Django 2.2.6 on 2019-12-19 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cards',
            name='card_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Кол-во карточек'),
        ),
    ]
